"""Turns assets/gilded_sword/gilded_sword.blend into shared/gilded_sword_model.h (the triangles the game draws, with a colour each).

    python3.11 tools/gilded_sword/export_gilded_sword.py          (or: blender -b assets/gilded_sword/gilded_sword.blend --python tools/gilded_sword/export_gilded_sword.py)

Points are written in the game's limb units (a hundredth of a game unit: the game draws Link's hand, and so the sword in it, at that scale), with the
grip at the origin and the blade along +X. Each triangle is three points and one colour: the material's colour with a fixed light baked in (a warm key
light from the front and a cool fill from behind, so both flat faces of the blade read), because the game draws these with plain vertex colours.
"""
import math
import os
import sys

import bpy
from mathutils import Vector

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)
import build_gilded_sword as g  # noqa: E402

BLEND = os.path.join(ROOT, "assets", "gilded_sword", "gilded_sword.blend")
OUT = os.path.join(ROOT, "shared", "gilded_sword_model.h")
UNITS = 100.0 * 100.0       # Blender metres -> game units (x100) -> limb units (x100)
KEY = Vector((0.35, -0.45, 0.82)).normalized()
FILL = Vector((-0.25, 0.35, -0.9)).normalized()


def triangles(name):
    ob = bpy.data.objects[name]
    me = ob.data
    me.calc_loop_triangles()
    rows = []
    for lt in me.loop_triangles:
        pts = [me.vertices[vi].co * UNITS for vi in lt.vertices]
        n = lt.normal.normalized()
        base = g.MATS[lt.material_index if lt.material_index < len(g.MATS) else 0][1]
        shade = 0.58 + 0.34 * max(0.0, n.dot(KEY)) + 0.18 * max(0.0, n.dot(FILL))
        # a touch of gold-warm in the light and blue in the shadow, like the game's painted models
        warm = 0.06 * max(0.0, n.dot(KEY))
        cool = 0.05 * (1.0 - max(0.0, n.dot(KEY)))
        rgb = [min(255, int(round(255 * c))) for c in (base[0] * shade + warm, base[1] * shade + warm * 0.6, base[2] * shade + cool)]
        rows.append((pts, rgb))
    return rows


def emit(rows):
    lines = []
    for pts, rgb in rows:
        coords = ", ".join("%d" % round(c) for p in pts for c in (p.x, p.y, p.z))
        lines.append("    {{%s}, {%d, %d, %d}}," % (coords, *rgb))
    return "\n".join(lines)


def main():
    if bpy.data.filepath != BLEND:
        bpy.ops.wm.open_mainfile(filepath=BLEND)
    blade, hilt, scab = triangles("GildedBlade"), triangles("GildedHilt"), triangles("GildedScabbard")
    text = """#pragma once
// GENERATED by tools/gilded_sword/export_gilded_sword.py from assets/gilded_sword/gilded_sword.blend. Do not edit by hand: change the .blend (or
// build_gilded_sword.py) and export again.
// The Gilded Sword: the grip is the origin and the blade runs along +X. Points are in the game's limb units (a hundredth of a game unit), colours have
// a fixed light baked in. kBlade and kHilt together are the sword; kHilt and kScabbard are the sword stowed on the back.
#include <cstdint>

namespace royale {
namespace gilded_sword_model {

struct Tri { int16_t p[9]; uint8_t rgb[3]; };

// Where the blade starts and ends along X, and the pommel end of the grip (limb units): the game puts its hit trail along the blade.
constexpr float kBladeStart = %.1ff, kBladeTip = %.1ff, kGripEnd = %.1ff;

constexpr Tri kBlade[] = {
%s
};
constexpr int kBladeCount = %d;

constexpr Tri kHilt[] = {
%s
};
constexpr int kHiltCount = %d;

constexpr Tri kScabbard[] = {
%s
};
constexpr int kScabbardCount = %d;

} // namespace gilded_sword_model
} // namespace royale
""" % (g.BLADE_START * 100, g.BLADE_TIP * 100, g.GRIP_END * 100, emit(blade), len(blade), emit(hilt), len(hilt), emit(scab), len(scab))
    with open(OUT, "w") as fh:
        fh.write(text)
    print("wrote", OUT, len(blade), "blade,", len(hilt), "hilt,", len(scab), "scabbard triangles")


if __name__ == "__main__":
    main()
