"""Turns assets/glider/glider.blend into shared/glider_model.h (the triangles the game draws, and the glider's measures).

    python3.11 tools/glider/export_glider.py          (or: blender -b assets/glider/glider.blend --python tools/glider/export_glider.py)

Everything is written in game units and the game's axes (X to the glider's left, Y up, Z forward), with the handle bar at the origin.
Each triangle is three points, the outward direction of its face (the game lights it itself and draws both sides) and a colour index
(see MATS in build_glider.py: the wing's stripes are the two colours of the player's colour scheme).
"""
import os
import sys

import bpy
from mathutils import Matrix, Vector

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)
import build_glider  # noqa: E402

BLEND = os.path.join(ROOT, "assets", "glider", "glider.blend")
OUT = os.path.join(ROOT, "shared", "glider_model.h")
C = Matrix(((1, 0, 0), (0, 0, 1), (0, -1, 0)))   # Blender (Z up, facing -Y) to game (Y up, facing +Z)


def triangles(name):
    ob = bpy.data.objects[name]
    me = ob.data
    me.calc_loop_triangles()
    rows = []
    for lt in me.loop_triangles:
        pts = [(C @ me.vertices[vi].co) * 100.0 for vi in lt.vertices]
        n = (C @ lt.normal).normalized()
        rows.append((pts, n, lt.material_index))
    return rows


def emit(rows):
    lines = []
    for pts, n, mat in rows:
        coords = ", ".join("%.2ff" % c for p in pts for c in (p.x, p.y, p.z))
        lines.append("    {{%s}, {%d, %d, %d}, %d}," % (coords, round(n.x * 127), round(n.y * 127), round(n.z * 127), mat))
    return "\n".join(lines)


def main():
    if bpy.data.filepath != BLEND:
        bpy.ops.wm.open_mainfile(filepath=BLEND)
    frame, wing = triangles("GliderFrame"), triangles("GliderWing")
    g = build_glider
    text = """#pragma once
// GENERATED by tools/glider/export_glider.py from assets/glider/glider.blend. Do not edit by hand: change the .blend (or build_glider.py) and export again.
// The skydiving glider: a hang glider with the handle bar at the origin (X to its left, Y up, Z forward, game units).
#include <cstdint>

namespace royale {
namespace glider_model {

// Colour indices: 0 wood, 1 leather grip, 2 gold, 3 wing stripe A, 4 wing stripe B, 5 under A, 6 under B, 7 dark wood.
struct Tri { float p[9]; int8_t n[3]; uint8_t colour; };

// The wing's corners (the right wing; the left is the mirror image) and where the grips run along the handle bar.
constexpr float kNose[3] = {%.1ff, %.1ff, %.1ff}, kTail[3] = {%.1ff, %.1ff, %.1ff}, kTip[3] = {%.1ff, %.1ff, %.1ff};
constexpr float kGripInner = %.1ff, kGripOuter = %.1ff;

constexpr Tri kFrame[] = {
%s
};
constexpr int kFrameCount = %d;

constexpr Tri kWing[] = {
%s
};
constexpr int kWingCount = %d;

} // namespace glider_model
} // namespace royale
""" % (*g.NOSE, *g.TAIL, *g.TIP, g.GRIP_INNER, g.GRIP_OUTER, emit(frame), len(frame), emit(wing), len(wing))
    with open(OUT, "w") as fh:
        fh.write(text)
    print("wrote", OUT, len(frame), "frame triangles,", len(wing), "wing triangles")


if __name__ == "__main__":
    main()
