#pragma once
// GENERATED by tools/cart/export_cart.py from assets/cart/cart.blend. Do not edit by hand.
//
// The Lon Lon Buggy's measures, in game units (Y up, facing +Z, its left +X, the wheels standing on y = 0). Plain numbers, so the
// physics, the server and the bots use the same cart the game draws (shared/vehicle.h).

namespace royale {
namespace cart {

enum Part : int { kBody, kWheelFL, kWheelFR, kWheelBL, kWheelBR, kHandlebar, kPartCount };
struct P3 { float x, y, z; };
// The point each part turns about: the wheels about their axles (front ones also steer), the handlebar about its column.
inline constexpr P3 kPivot[kPartCount] = { {0.00f, 0.00f, 0.00f}, {43.00f, 22.00f, 46.00f}, {-43.00f, 22.00f, 46.00f}, {43.00f, 22.00f, -42.00f}, {-43.00f, 22.00f, -42.00f}, {0.00f, 56.00f, 40.00f} };
constexpr float kWheelRadius = 22.00f;
constexpr float kWheelBase = 88.00f;     // front axle to back axle
constexpr float kTrack = 86.00f;         // between the left and right wheels
constexpr float kFrontAxle = 46.00f, kBackAxle = -42.00f;
// Where riders sit (the top of the saddle) and where they stand to get on and off (the driver on the left, the passenger on the right).
inline constexpr P3 kSeatDriver = {0.00f, 53.50f, 6.00f};
inline constexpr P3 kSeatPassenger = {0.00f, 53.50f, -33.00f};
inline constexpr P3 kExitDriver = {62.00f, 0.00f, 6.00f};
inline constexpr P3 kExitPassenger = {-62.00f, 0.00f, -33.00f};
inline constexpr P3 kExhaust = {-12.00f, 98.00f, -60.00f};
inline constexpr P3 kFlagTop = {27.00f, 110.00f, -62.00f};
// The box it fills.
constexpr float kMinX = -51.90f, kMaxX = 51.90f, kMinY = 0.00f, kMaxY = 113.00f, kMinZ = -92.00f, kMaxZ = 84.00f;

} // namespace cart
} // namespace royale
