// Generated by scripts/make_item_surface_maps.py; do not edit.
#pragma once
#include <cstdint>
namespace royale::item_surface {
inline constexpr unsigned kSize = 1;
inline constexpr uint8_t kokiri_sword_normal[] = {
    128,128,255,255,
};
inline constexpr uint8_t kokiri_sword_bump[] = {
    128,128,128,255,
};
inline constexpr uint8_t master_sword_normal[] = {
    128,128,255,255,
};
inline constexpr uint8_t master_sword_bump[] = {
    128,128,128,255,
};
inline constexpr uint8_t biggoron_sword_normal[] = {
    128,128,255,255,
};
inline constexpr uint8_t biggoron_sword_bump[] = {
    128,128,128,255,
};
inline constexpr uint8_t deku_shield_normal[] = {
    128,128,255,255,
};
inline constexpr uint8_t deku_shield_bump[] = {
    128,128,128,255,
};
inline constexpr uint8_t hylian_shield_normal[] = {
    128,128,255,255,
};
inline constexpr uint8_t hylian_shield_bump[] = {
    128,128,128,255,
};
inline constexpr uint8_t mirror_shield_normal[] = {
    128,128,255,255,
};
inline constexpr uint8_t mirror_shield_bump[] = {
    128,128,128,255,
};
} // namespace royale::item_surface
