"""Verify native engine patches, including item rendering, against pinned source.

Uses only files touched by patches and leaves source checkouts unchanged. Also
checks the stack can be reversed; no engine build or downloaded SDK is required.
"""
from pathlib import Path
import re
import subprocess
import tempfile

root = Path(__file__).resolve().parents[1]
engine = root/'third_party/Shipwright-Android'
for repo, folder in ((engine, root/'patches'), (engine/'libultraship', root/'patches/libultraship')):
    patches = sorted(folder.glob('*.patch'))
    # Android Java patches contain mixed historical line endings. Their real
    # checkout is checked by the APK build; here check the native renderer stack.
    texts = [''.join('diff --git '+section for section in p.read_text().split('diff --git ')[1:]
                     if not section.startswith('a/Android/')) for p in patches]
    paths = {n for t in texts for n in re.findall(r'^--- a/(.+)$', t, re.M)}
    with tempfile.TemporaryDirectory(prefix='item-patch-check-', dir=root.parent) as scratch:
        dest = Path(scratch)
        assert dest.resolve().parent == root.parent.resolve()
        for name in paths:
            old = subprocess.run(['git', '-C', str(repo), 'show', 'HEAD:'+name], capture_output=True)
            if old.returncode: continue  # generated by an earlier patch
            p = dest/name
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_bytes(old.stdout.replace(b'\r\n', b'\n'))
        for patch, text in zip(patches, texts):
            if not text.strip(): continue
            # Feed LF patches through stdin for platform-independent verification.
            print('Checking', patch.name, flush=True)
            subprocess.run(['git', '-C', str(dest), 'apply', '--unsafe-paths', '--ignore-space-change', '--whitespace=nowarn', '-'],
                           input=text.encode(), check=True)
        for patch, text in reversed(list(zip(patches, texts))):
            if not text.strip(): continue
            subprocess.run(['git', '-C', str(dest), 'apply', '-R', '--unsafe-paths', '--ignore-space-change', '--whitespace=nowarn', '-'],
                           input=text.encode(), check=True)
        print(f'{repo.name}: native changes in {len(patches)} patches apply and reverse cleanly')
