#!/usr/bin/env python3
"""Turn the boulder texture into the stone colouring the game's boulders and rocks are painted with.

Our models are coloured per vertex, not textured, so the picture is shrunk to a 64 x 64 tile (the size of an N64 texture) and written into a
C++ header; meshes.h samples it at each vertex of a stone, from three sides at once, so the boulders take on its colours and its mottling.

  assets/boulder/boulder_texture.png  (a 256 x 256 copy of the Meshy texture from the project's "boulder" folder)
    -> shared/boulder_texture.h

Needs Pillow. Usage: make_boulder_texture.py [path/to/a/new/texture.png]   (a new texture also replaces the 256 x 256 copy)
"""
import os, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "assets", "boulder", "boulder_texture.png")
HEADER = os.path.join(ROOT, "shared", "boulder_texture.h")
SIZE = 64


def main():
    if len(sys.argv) > 1:
        Image.open(sys.argv[1]).convert("RGB").resize((256, 256), Image.LANCZOS).save(SOURCE)
    img = Image.open(SOURCE).convert("RGB").resize((SIZE, SIZE), Image.LANCZOS)
    px = [img.getpixel((x, y)) for y in range(SIZE) for x in range(SIZE)]
    n = len(px)
    mean = [sum(p[i] for p in px) / n for i in range(3)]
    rows = []
    for y in range(SIZE):
        rows.append("    " + ",".join("%d,%d,%d" % px[y * SIZE + x] for x in range(SIZE)) + ",")
    with open(HEADER, "w") as f:
        f.write("// Generated by scripts/make_boulder_texture.py from assets/boulder/boulder_texture.png. Do not edit.\n")
        f.write("#pragma once\n#include <cstdint>\nnamespace royale {\n")
        f.write("constexpr int kBoulderTexSize = %d;\n" % SIZE)
        f.write("constexpr float kBoulderTexMean[3] = {%.1ff, %.1ff, %.1ff}; // its average colour\n" % tuple(mean))
        f.write("// %d x %d pixels, rows from the top, red green blue.\n" % (SIZE, SIZE))
        f.write("inline const uint8_t kBoulderTex[kBoulderTexSize * kBoulderTexSize * 3] = {\n")
        f.write("\n".join(rows))
        f.write("\n};\n} // namespace royale\n")
    print("wrote", HEADER)


if __name__ == "__main__":
    main()
