#!/usr/bin/env python3
"""Pack Maya's cleaned mono 16 kHz recordings into the game's audio format.
Rebuild with: python scripts/make_maya_sounds.py
The original family video is not needed or embedded in the game.
"""
from pathlib import Path
import wave, struct
ROOT=Path(__file__).resolve().parents[1]
NAMES=(('maya_happy','Happy vocalization'),('maya_playful','Playful response'))
def main():
    out=['#pragma once','// Generated by scripts/make_maya_sounds.py. Maya recordings, mono PCM16, 16 kHz.','#include <cstdint>','namespace royale { namespace maya_snd {','constexpr int kRate=16000;','enum ClipId { kHappy, kPlayful, kClipCount };']
    counts=[]
    for name,label in NAMES:
        with wave.open(str(ROOT/'assets/maya/sounds'/f'{name}.wav')) as w:
            assert (w.getnchannels(),w.getsampwidth(),w.getframerate())==(1,2,16000)
            samples=[v[0] for v in struct.iter_unpack('<h',w.readframes(w.getnframes()))]
        assert 0<len(samples)<16000*3 and max(abs(v) for v in samples)<=24576
        counts.append(len(samples));out.append(f'inline constexpr int16_t k_{name}[{len(samples)}]={{')
        for i in range(0,len(samples),40):out.append('    '+','.join(str(v) for v in samples[i:i+40])+',')
        out.append('};')
    out += ['struct Clip { const char* label; const int16_t* data; int count; };','inline constexpr Clip kClips[kClipCount]={']
    for (name,label),count in zip(NAMES,counts):out.append(f'    {{"{label}",k_{name},{count}}},')
    out += ['};','} } // namespace royale::maya_snd']
    (ROOT/'shared/maya_sounds.h').write_text('\n'.join(out)+'\n')
    print('Packed two Maya voice clips:',counts,'samples')
if __name__=='__main__':main()
