#!/usr/bin/env python3
"""Turns Lilo's recorded sounds into shared/lilo_sounds.h.

  assets/lilo/sounds/cat_NN.wav   (16-bit mono 16 kHz clips of the real Lilo, already cleaned, trimmed and normalised)
  assets/lilo/fart/rigid_fart.wav (her accident: a free recording, see assets/lilo/fart/CREDITS.md; also 16-bit mono 16 kHz)
    -> shared/lilo_sounds.h

Usage: make_lilo_sounds.py   (no arguments; to add a clip put a .wav in that folder and run it again)
"""
import glob, os, wave

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "lilo", "sounds")
FART = os.path.join(ROOT, "assets", "lilo", "fart", "rigid_fart.wav")
HEADER = os.path.join(ROOT, "shared", "lilo_sounds.h")

def clip(path, out):
    w = wave.open(path)
    assert (w.getnchannels(), w.getsampwidth(), w.getframerate()) == (1, 2, 16000), path + ": need 16-bit mono 16 kHz"
    data = w.readframes(w.getnframes())
    samples = [int.from_bytes(data[i:i + 2], "little", signed=True) for i in range(0, len(data), 2)]
    name = os.path.splitext(os.path.basename(path))[0]
    out.append("inline constexpr int16_t k_%s[%d] = {\n" % (name, len(samples)))
    for i in range(0, len(samples), 40):
        out.append("    " + ",".join(str(s) for s in samples[i:i + 40]) + ",\n")
    out.append("};\n")
    return name

def main():
    names, out = [], []
    for path in sorted(glob.glob(os.path.join(SRC, "*.wav"))):
        names.append(clip(path, out))
    fart = clip(FART, out)
    with open(HEADER, "w") as f:
        f.write("// Generated by scripts/make_lilo_sounds.py from assets/lilo/sounds/*.wav. Do not edit.\n")
        f.write("// Seven short recordings of the real Lilo (16-bit mono, 16 kHz).\n#pragma once\n#include <cstdint>\nnamespace royale {\nnamespace lilo_snd {\n")
        f.write("constexpr int kRate = 16000;\n")
        f.write("".join(out))
        f.write("struct Clip { const int16_t* data; int count; };\n")
        f.write("inline constexpr Clip kClips[%d] = {\n" % len(names))
        for n in names:
            f.write("    { k_%s, static_cast<int>(sizeof(k_%s) / sizeof(int16_t)) },\n" % (n, n))
        f.write("};\n")
        f.write("// Her accident (\"Rigid Fart\" from SoundBible.com, CC BY 3.0; credit in assets/lilo/fart/CREDITS.md). Not one of the mews above.\n")
        f.write("inline constexpr Clip kFart = { k_%s, static_cast<int>(sizeof(k_%s) / sizeof(int16_t)) };\n" % (fart, fart))
        f.write("} // namespace lilo_snd\n} // namespace royale\n")
    print("wrote", HEADER, len(names), "clips and the fart")

main()
