"""Generate tileable OpenGL normal maps and independent bump maps for Link's gear.

Neutral fallback maps. Actual relief is generated by shared/asset_relief.h from loaded game assets, not replacements
for the existing colour textures. Run from any directory; outputs are deterministic.
"""
from pathlib import Path
import math
import struct
import zlib

ROOT = Path(__file__).resolve().parents[1]
SIZE = 1
ITEMS = ('kokiri_sword', 'master_sword', 'biggoron_sword', 'deku_shield', 'hylian_shield', 'mirror_shield')


def heights(name, size=SIZE):
    # Real detail is derived at runtime from the user's loaded OTR texture.
    # Keep a neutral fallback; invented periodic stripes distort the paint.
    return [[.5] * size for _ in range(size)]


def encode_maps(h, strength=3):
    n, bump = bytearray(), bytearray()
    size = len(h)
    for y in range(size):
        for x in range(size):
            dx = (h[y][(x+1)%size] - h[y][(x-1)%size])*strength
            dy = (h[(y+1)%size][x] - h[(y-1)%size][x])*strength
            length = math.sqrt(dx*dx+dy*dy+1)
            n.extend(round((a/length*.5+.5)*255) for a in (-dx, -dy, 1))
            n.append(255)
            b = max(0, min(255, round(h[y][x]*255)))
            bump.extend((b, b, b, 255))
    return bytes(n), bytes(bump)


def png(path, data, size=SIZE):
    def chunk(kind, value):
        return struct.pack('>I', len(value))+kind+value+struct.pack('>I', zlib.crc32(kind+value))
    rows = b''.join(b'\0'+data[y*size*4:(y+1)*size*4] for y in range(size))
    path.write_bytes(b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR', struct.pack('>IIBBBBB', size, size, 8, 6, 0, 0, 0))
                     +chunk(b'IDAT', zlib.compress(rows, 9))+chunk(b'IEND', b''))


def main():
    dest = ROOT / 'assets' / 'items' / 'surface_maps'
    dest.mkdir(parents=True, exist_ok=True)
    lines = ['// Generated by scripts/make_item_surface_maps.py; do not edit.', '#pragma once',
             '#include <cstdint>', 'namespace royale::item_surface {', f'inline constexpr unsigned kSize = {SIZE};']
    for name in ITEMS:
        normal, bump = encode_maps(heights(name))
        for suffix, data in (('normal', normal), ('bump', bump)):
            png(dest / f'{name}_{suffix}.png', data)
            lines.append(f'inline constexpr uint8_t {name}_{suffix}[] = {{')
            lines.extend('    '+','.join(str(b) for b in data[i:i+32])+',' for i in range(0, len(data), 32))
            lines.append('};')
    lines.append('} // namespace royale::item_surface')
    (ROOT / 'shared' / 'item_surface_maps.h').write_text('\n'.join(lines)+'\n')
    print(f'Generated {len(ITEMS)*2} maps ({SIZE}x{SIZE}) and shared/item_surface_maps.h')


if __name__ == '__main__':
    main()
