"""Makes the Gilded Sword's menu icon from Tee's reference picture (assets/gilded_sword/gilded_sword_reference.jpg).

    python3 scripts/make_gilded_sword_icon.py

Takes the white background away (flood fill from the edges), crops to the sword, pads to a square and shrinks to 64x64 with a soft edge, then writes
mod/Royale/gilded_sword_icon.h (RGBA bytes the mod uploads as a texture) and assets/gilded_sword/gilded_sword_icon.png (a preview).
"""
import os
from collections import deque

from PIL import Image, ImageFilter

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
SRC = os.path.join(ROOT, "assets", "gilded_sword", "gilded_sword_reference.jpg")
SIZE = 64

im = Image.open(SRC).convert("RGB")
w, h = im.size
px = im.load()
bg = [[False] * w for _ in range(h)]
seen = deque()
def is_bg(x, y):
    r, g, b = px[x, y]
    return r > 232 and g > 232 and b > 232
for x in range(w):
    for y in (0, h - 1):
        if is_bg(x, y): bg[y][x] = True; seen.append((x, y))
for y in range(h):
    for x in (0, w - 1):
        if is_bg(x, y) and not bg[y][x]: bg[y][x] = True; seen.append((x, y))
while seen:
    x, y = seen.popleft()
    for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
        nx, ny = x + dx, y + dy
        if 0 <= nx < w and 0 <= ny < h and not bg[ny][nx] and is_bg(nx, ny):
            bg[ny][nx] = True
            seen.append((nx, ny))
alpha = Image.new("L", (w, h), 255)
ap = alpha.load()
for y in range(h):
    for x in range(w):
        if bg[y][x]: ap[x, y] = 0
alpha = alpha.filter(ImageFilter.MinFilter(3)).filter(ImageFilter.GaussianBlur(0.8))   # eat the white fringe, soften the edge
rgba = im.convert("RGBA")
rgba.putalpha(alpha)
box = rgba.getbbox()
rgba = rgba.crop(box)
side = max(rgba.size) + 6
sq = Image.new("RGBA", (side, side), (0, 0, 0, 0))
sq.paste(rgba, ((side - rgba.width) // 2, (side - rgba.height) // 2))
icon = sq.resize((SIZE, SIZE), Image.LANCZOS)
icon.save(os.path.join(ROOT, "assets", "gilded_sword", "gilded_sword_icon.png"))
data = list(icon.tobytes())
rows = []
for i in range(0, len(data), 32):
    rows.append("    " + ",".join(str(v) for v in data[i:i + 32]) + ",")
with open(os.path.join(ROOT, "mod", "Royale", "gilded_sword_icon.h"), "w") as f:
    f.write("// Generated by scripts/make_gilded_sword_icon.py from assets/gilded_sword/gilded_sword_reference.jpg. Do not edit.\n#pragma once\n#include <cstdint>\nnamespace royale {\nconstexpr int kGildedIconSize = %d;\ninline const uint8_t kGildedIconRgba[%d * %d * 4] = {\n%s\n};\n}\n" % (SIZE, SIZE, SIZE, "\n".join(rows)))
print("wrote icon", icon.size)
