#!/usr/bin/env python3
"""Turns the recordings of the real baby Avriella into shared/avriella_sounds.h.

  assets/avriella/sounds/avriella_NN.wav   (any 16-bit PCM wav; the 15 originals are 44.1 kHz mono)
    -> assets/avriella/sounds/avriella_NN.wav is rewritten as 16-bit mono 16 kHz (trimmed, peak-normalised)
    -> shared/avriella_sounds.h

Usage: make_avriella_sounds.py [folder with the original wavs]
  With a folder, the originals in it are converted into assets/avriella/sounds first. With no argument the wavs already there are used
  (so to add a clip, put a 16 kHz or any-rate wav in that folder and run it again). Needs numpy.
"""
import glob, os, shutil, sys, wave
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "avriella", "sounds")
HEADER = os.path.join(ROOT, "shared", "avriella_sounds.h")
RATE = 16000

def load(path):
    w = wave.open(path)
    assert w.getsampwidth() == 2, path + ": need 16-bit PCM"
    x = np.frombuffer(w.readframes(w.getnframes()), dtype="<i2").astype(np.float64)
    if w.getnchannels() > 1:
        x = x.reshape(-1, w.getnchannels()).mean(axis=1)
    return x, w.getframerate()

def convert(x, rate):
    if rate != RATE:   # plain linear resample after a short moving-average low-pass (the game only needs a baby's voice, not hi-fi)
        if rate > RATE:
            k = max(1, int(round(rate / RATE)))
            x = np.convolve(x, np.ones(k) / k, mode="same")
        n = int(len(x) * RATE / rate)
        x = np.interp(np.arange(n) * rate / RATE, np.arange(len(x)), x)
    loud = np.abs(x) > 0.02 * max(1.0, np.abs(x).max())
    idx = np.flatnonzero(loud)
    if len(idx):
        a, b = max(0, idx[0] - int(0.03 * RATE)), min(len(x), idx[-1] + int(0.06 * RATE))
        x = x[a:b]
    fade = int(0.02 * RATE)   # no click at the ends
    x[:fade] *= np.linspace(0, 1, fade)
    x[-fade:] *= np.linspace(1, 0, fade)
    return np.round(x * (28000.0 / max(1.0, np.abs(x).max()))).astype(np.int16)

def main():
    if len(sys.argv) > 1:
        for p in sorted(glob.glob(os.path.join(sys.argv[1], "avriella_*.wav"))):
            x, r = load(p)
            pcm = convert(x, r)
            with wave.open(os.path.join(SRC, os.path.basename(p)), "wb") as w:
                w.setnchannels(1); w.setsampwidth(2); w.setframerate(RATE); w.writeframes(pcm.tobytes())
    names, out = [], []
    for p in sorted(glob.glob(os.path.join(SRC, "avriella_*.wav"))):
        x, r = load(p)
        assert r == RATE, p + ": run with the folder of originals once to convert it"
        s = x.astype(int)
        name = os.path.splitext(os.path.basename(p))[0]
        names.append(name)
        out.append("inline constexpr int16_t k_%s[%d] = {\n" % (name, len(s)))
        for i in range(0, len(s), 40):
            out.append("    " + ",".join(str(v) for v in s[i:i + 40]) + ",\n")
        out.append("};\n")
    with open(HEADER, "w") as f:
        f.write("// Generated by scripts/make_avriella_sounds.py from assets/avriella/sounds/*.wav. Do not edit.\n")
        f.write("// Recordings of the real baby Avriella (16-bit mono, 16 kHz). The clips are in file-number order.\n#pragma once\n#include <cstdint>\nnamespace royale {\nnamespace avriella_snd {\n")
        f.write("constexpr int kRate = 16000;\n")
        f.write("".join(out))
        f.write("struct Clip { int number; const int16_t* data; int count; };\n")
        f.write("inline constexpr Clip kClips[%d] = {\n" % len(names))
        for n in names:
            f.write("    { %d, k_%s, static_cast<int>(sizeof(k_%s) / sizeof(int16_t)) },\n" % (int(n.split("_")[1]), n, n))
        f.write("};\n} // namespace avriella_snd\n} // namespace royale\n")
    print("wrote", HEADER, len(names), "clips")

main()
