#!/usr/bin/env python3
"""Synthesises the cartoon 'someone talking on the phone' babble for Maya's video call (an original sound, no recordings).
Wah-wah syllables from a buzzing voice through a sweeping vowel filter, squeezed to a phone's band. Writes shared/maya_phone.h.
Rebuild with: python scripts/make_maya_phone_sound.py   (needs numpy)
"""
from pathlib import Path
import numpy as np
RATE=16000
ROOT=Path(__file__).resolve().parents[1]
def build():
    rng=np.random.default_rng(7)
    out=np.zeros(int(RATE*2.0));t0=0.0
    sylls=[(.22,150,1.12),(.16,170,.95),(.28,140,1.2),(.18,180,.9),(.24,160,1.25),(.14,190,1.0),(.3,150,.85),(.2,175,1.15)]
    for dur,f0,glide in sylls:
        n=int(RATE*dur);t=np.arange(n)/RATE;u=t/dur
        pitch=f0*(1+(glide-1)*np.sin(np.pi*u)*1.4)*(1+.03*np.sin(2*np.pi*6*t))
        phase=2*np.pi*np.cumsum(pitch)/RATE
        voice=sum(np.sin(k*phase)/k for k in range(1,14))             # buzzy harmonics
        # a vowel filter that sweeps (wah): two resonant bands moving with the syllable
        spec=np.fft.rfft(voice);fr=np.fft.rfftfreq(n,1/RATE)
        c1=350+500*np.sin(np.pi*u).mean();c2=900+900*np.sin(np.pi*np.clip(u*1.2,0,1)).mean()
        gain=np.exp(-((fr-c1)/220)**2)+.7*np.exp(-((fr-c2)/350)**2)+.05
        s=np.fft.irfft(spec*gain,n)
        env=np.sin(np.pi*np.clip(u*1.05,0,1))**.7
        s*=env/(np.abs(s).max()+1e-9)
        start=int(RATE*t0)
        if start+n>len(out):break
        out[start:start+n]+=s*(.8+.2*rng.random())
        t0+=dur+.045+.06*rng.random()
    # a phone's narrow band (about 400 to 3000 Hz) and a little crunch
    spec=np.fft.rfft(out);fr=np.fft.rfftfreq(len(out),1/RATE)
    spec*=(fr>400)*(fr<3000)*(1/(1+(fr<550)*.0))
    out=np.fft.irfft(spec,len(out));out=np.tanh(out*2.2/np.abs(out).max())
    out*=np.minimum(1,np.minimum(np.arange(len(out)),np.arange(len(out))[::-1])/200)
    out=out/np.abs(out).max()*.72*32767
    return out.astype(np.int16)
def main():
    s=build()
    lines=['#pragma once','// Generated by scripts/make_maya_phone_sound.py: cartoon phone babble for Maya\'s video call, mono PCM16, 16 kHz, made from scratch.','#include <cstdint>','namespace royale { namespace maya_phone {','constexpr int kRate=16000;',f'constexpr int kCount={len(s)};',f'inline constexpr int16_t kData[{len(s)}]={{']
    for i in range(0,len(s),40):lines.append('    '+','.join(str(int(v)) for v in s[i:i+40])+',')
    lines+=['};','} } // namespace royale::maya_phone']
    (ROOT/'shared/maya_phone.h').write_text('\n'.join(lines)+'\n')
    print('wrote',len(s),'samples')
if __name__=='__main__':main()
