"""Export menu art/font into bounded RGBA16 and IA8 native texture tiles.

Run with Pillow. Original art remains in assets/menu/war_table. No engine or ROM
assets are copied into the repository. RGBA16 is explicitly big endian.
"""
from pathlib import Path
import hashlib
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'assets/menu/war_table'
OUT = ROOT / 'shared/war_table_assets.h'

def tiled_rgba16(image):
    image = image.convert('RGBA')
    data = bytearray()
    for ty in range(0, image.height, 32):
        for tx in range(0, image.width, 32):
            for y in range(32):
                for x in range(32):
                    r, g, b, a = image.getpixel((min(tx+x,image.width-1), min(ty+y,image.height-1)))
                    n = (r >> 3) << 11 | (g >> 3) << 6 | (b >> 3) << 1 | (a >= 128)
                    data.extend(n.to_bytes(2, 'big'))
    return bytes(data)

def array(name, data):
    rows = [','.join(str(v) for v in data[i:i+32]) for i in range(0, len(data), 32)]
    return f'alignas(8) inline const unsigned char {name}[] = {{\n' + ',\n'.join(rows) + '\n};\n'

def main():
    # Engine uses 32x32 tiles (2 KiB each), comfortably inside native TMEM limits.
    background = Image.open(ASSETS / 'background-source.png').convert('RGBA').resize((320,192), Image.Resampling.LANCZOS)
    background.save(ASSETS / 'background-runtime.png')
    out = '#pragma once\n// Generated by tools/build_war_table_assets.py; edit source assets, then regenerate.\nnamespace royale::wartable::art {\n'
    out += array('background', tiled_rgba16(background))
    for name, source, size in [('body','Vera.ttf',18), ('heading','VeraBd.ttf',21)]:
        font = ImageFont.truetype(str(ASSETS / source), size)
        glyphs = bytearray()
        widths = []
        sheet = Image.new('L',(24*16,32*6))
        for i in range(96):
            c = chr(i+32)
            tile = Image.new('L',(24,32))
            ImageDraw.Draw(tile).text((1,1),c,font=font,fill=255,anchor='lt')
            widths.append(min(24, round(font.getlength(c))+1))
            # IA8: white intensity and four-bit coverage, so edges alpha blend.
            glyphs.extend(0xf0 | (a >> 4) for a in tile.tobytes())
            sheet.paste(tile,((i%16)*24,(i//16)*32))
        sheet.save(ASSETS / (name+'-atlas.png'))
        out += array(name, glyphs) + array(name+'Widths', widths)
    out += '}\n'
    OUT.write_text(out,encoding='utf-8')
    print(f'{OUT.name}: {OUT.stat().st_size} bytes; SHA256 {hashlib.sha256(OUT.read_bytes()).hexdigest()}')

if __name__ == '__main__':
    main()
