"""Turns assets/cart/cart.blend into shared/cart_model.h (the mesh and texture the game draws) and shared/cart_geometry.h (its measures, which the
physics, the server and the bots use too).

    python3 tools/cart/export_cart.py          (or: blender -b assets/cart/cart.blend --python tools/cart/export_cart.py)

What it writes, all in game units and the game's axes (Y up, the cart facing +Z, its left +X, the ground at y = 0):
  - each rigid part (the body, the four wheels, the handlebar) with the point it turns about;
  - the vertices, grouped into batches of at most 32 (what the N64 graphics chip loads at a time), each with a texel coordinate and a normal
    (the game lights them itself, from the cart's tilt and the sun), and the triangles of each batch;
  - the 64x32 texture as RGBA16 (the N64's 5-5-5-1 format);
  - the seats, the places riders get on and off, the chimney's top and the size of the cart.
"""
import os
import sys

import bpy
from mathutils import Matrix, Vector

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)
import build_cart  # noqa: E402  (the measures and texture size live there)

BLEND = os.path.join(ROOT, "assets", "cart", "cart.blend")
MODEL = os.path.join(ROOT, "shared", "cart_model.h")
GEOMETRY = os.path.join(ROOT, "shared", "cart_geometry.h")
SCALE = 100.0        # metres in Blender to game units
MAX_BATCH = 32
PARTS = ["CartBody", "WheelFL", "WheelFR", "WheelBL", "WheelBR", "Handlebar"]
ENUM = ["kBody", "kWheelFL", "kWheelFR", "kWheelBL", "kWheelBR", "kHandlebar"]

C = Matrix(((1, 0, 0), (0, 0, 1), (0, -1, 0)))   # Blender (Z up, facing -Y) to game (Y up, facing +Z)


def to_game(v):
    return C @ Vector(v)


def rgba5551(pix_rgba, w, h):
    out = bytearray()
    for row in range(h - 1, -1, -1):
        for col in range(w):
            i = (row * w + col) * 4
            r, g, b = (min(31, max(0, int(round(pix_rgba[i + k] * 31)))) for k in range(3))
            v = (r << 11) | (g << 6) | (b << 1) | 1
            out += bytes(((v >> 8) & 0xFF, v & 0xFF))
    return out


def fmt_rows(values, per_line, indent="    "):
    return "\n".join(indent + ", ".join(values[i:i + per_line]) + "," for i in range(0, len(values), per_line))


def f(v):
    return "%.2ff" % v


def main():
    if bpy.data.filepath != BLEND:
        bpy.ops.wm.open_mainfile(filepath=BLEND)
    tw, th = build_cart.TEX_W, build_cart.TEX_H
    verts, batches, tris, pivots = [], [], [], []
    lo, hi = Vector((1e9, 1e9, 1e9)), Vector((-1e9, -1e9, -1e9))
    for part, name in enumerate(PARTS):
        obj = bpy.data.objects[name]
        me = obj.data
        me.calc_loop_triangles()
        uv = me.uv_layers.active.data
        normals = me.corner_normals
        pivot = to_game(obj.matrix_world.translation) * SCALE
        pivots.append(pivot)
        cur = None
        for lt in me.loop_triangles:
            cs = []
            for li, vi in zip(lt.loops, lt.vertices):
                p = to_game(me.vertices[vi].co) * SCALE
                n = to_game(normals[li].vector).normalized()
                u, v = uv[li].uv
                s, t = round(u * tw * 32), round((1.0 - v) * th * 32)
                world = p + pivot
                lo = Vector((min(lo.x, world.x), min(lo.y, world.y), min(lo.z, world.z)))
                hi = Vector((max(hi.x, world.x), max(hi.y, world.y), max(hi.z, world.z)))
                key = (vi, s, t, round(n.x * 127), round(n.y * 127), round(n.z * 127))
                cs.append((key, (p.x, p.y, p.z, key[3], key[4], key[5], s, t)))
            new = len({k for k, _ in cs if cur is None or k not in cur["map"]})
            if cur is None or len(cur["map"]) + new > MAX_BATCH:
                cur = {"part": part, "map": {}, "first": len(verts), "tris_first": len(tris)}
                batches.append(cur)
            idx = []
            for k, data in cs:
                if k not in cur["map"]:
                    cur["map"][k] = len(cur["map"])
                    verts.append(data)
                idx.append(cur["map"][k])
            tris.append(idx)
    for i, b in enumerate(batches):
        b["count"] = len(b["map"])
        b["tris_count"] = (batches[i + 1]["tris_first"] if i + 1 < len(batches) else len(tris)) - b["tris_first"]

    tex = rgba5551(list(bpy.data.images["cart_atlas"].pixels), tw, th)

    def point(name):
        return to_game(bpy.data.objects[name].matrix_world.translation) * SCALE

    # ---- the model ----------------------------------------------------------------------------------------------------------
    out = []
    out.append("#pragma once")
    out.append("// GENERATED by tools/cart/export_cart.py from assets/cart/cart.blend (made by tools/cart/build_cart.py). Do not edit by hand:")
    out.append("// change the Blender file or the build script and run the export again.")
    out.append("//")
    out.append("// The Lon Lon Buggy, low poly in the N64 style: %d vertices in %d batches, %d triangles, %d rigid parts, one %dx%d texture." %
               (len(verts), len(batches), len(tris), len(PARTS), tw, th))
    out.append("// Game units, Y up, facing +Z, wheels on y = 0. Each vertex is relative to its part's pivot (shared/cart_geometry.h has the pivots).")
    out.append("#include \"cart_geometry.h\"")
    out.append("#include <cstdint>")
    out.append("")
    out.append("namespace royale {")
    out.append("namespace cart {")
    out.append("")
    out.append("// A vertex: position (relative to its part's pivot), normal (x127) and texel coordinate (in 1/32 texels, the N64's S10.5).")
    out.append("struct Vert { float x, y, z; int8_t nx, ny, nz; int16_t s, t; };")
    out.append("// A batch: up to 32 vertices of one part loaded together and the triangles drawn from them (indices are within the batch).")
    out.append("struct Batch { uint8_t part; uint16_t firstVert; uint8_t vertCount; uint16_t firstTri; uint16_t triCount; };")
    out.append("")
    out.append("constexpr int kVertCount = %d;" % len(verts))
    out.append("inline constexpr Vert kVerts[kVertCount] = {")
    out.append(fmt_rows(["{%s, %s, %s, %d, %d, %d, %d, %d}" % (f(v[0]), f(v[1]), f(v[2]), v[3], v[4], v[5], v[6], v[7]) for v in verts], 3))
    out.append("};")
    out.append("constexpr int kBatchCount = %d;" % len(batches))
    out.append("inline constexpr Batch kBatches[kBatchCount] = {")
    out.append(fmt_rows(["{%d, %d, %d, %d, %d}" % (b["part"], b["first"], b["count"], b["tris_first"], b["tris_count"]) for b in batches], 4))
    out.append("};")
    out.append("constexpr int kTriCount = %d;" % len(tris))
    out.append("inline constexpr uint8_t kTris[kTriCount][3] = {")
    out.append(fmt_rows(["{%d, %d, %d}" % tuple(t) for t in tris], 10))
    out.append("};")
    out.append("")
    out.append("constexpr int kTexW = %d, kTexH = %d;" % (tw, th))
    out.append("// RGBA5551, big-endian, top row first.")
    out.append("alignas(8) inline constexpr uint8_t kTex[kTexW * kTexH * 2] = {")
    out.append(fmt_rows(["0x%02X" % b for b in tex], 24))
    out.append("};")
    out.append("")
    out.append("} // namespace cart")
    out.append("} // namespace royale")
    with open(MODEL, "w") as fh:
        fh.write("\n".join(out) + "\n")

    # ---- the measures ---------------------------------------------------------------------------------------------------------
    wheel = pivots[1]
    g = []
    g.append("#pragma once")
    g.append("// GENERATED by tools/cart/export_cart.py from assets/cart/cart.blend. Do not edit by hand.")
    g.append("//")
    g.append("// The Lon Lon Buggy's measures, in game units (Y up, facing +Z, its left +X, the wheels standing on y = 0). Plain numbers, so the")
    g.append("// physics, the server and the bots use the same cart the game draws (shared/vehicle.h).")
    g.append("")
    g.append("namespace royale {")
    g.append("namespace cart {")
    g.append("")
    g.append("enum Part : int { %s, kPartCount };" % ", ".join(ENUM))
    g.append("struct P3 { float x, y, z; };")
    g.append("// The point each part turns about: the wheels about their axles (front ones also steer), the handlebar about its column.")
    g.append("inline constexpr P3 kPivot[kPartCount] = { %s };" % ", ".join("{%s, %s, %s}" % (f(p.x), f(p.y), f(p.z)) for p in pivots))
    g.append("constexpr float kWheelRadius = %s;" % f(build_cart.WHEEL_R * SCALE))
    g.append("constexpr float kWheelBase = %s;     // front axle to back axle" % f(pivots[1].z - pivots[3].z))
    g.append("constexpr float kTrack = %s;         // between the left and right wheels" % f(pivots[1].x - pivots[2].x))
    g.append("constexpr float kFrontAxle = %s, kBackAxle = %s;" % (f(pivots[1].z), f(pivots[3].z)))
    g.append("// Where riders sit (the top of the saddle) and where they stand to get on and off (the driver on the left, the passenger on the right).")
    for name, cname in (("SeatDriver", "kSeatDriver"), ("SeatPassenger", "kSeatPassenger"), ("ExitDriver", "kExitDriver"),
                        ("ExitPassenger", "kExitPassenger"), ("Exhaust", "kExhaust"), ("FlagTop", "kFlagTop")):
        p = point(name)
        g.append("inline constexpr P3 %s = {%s, %s, %s};" % (cname, f(p.x), f(p.y), f(p.z)))
    g.append("// The box it fills.")
    g.append("constexpr float kMinX = %s, kMaxX = %s, kMinY = %s, kMaxY = %s, kMinZ = %s, kMaxZ = %s;" %
             (f(lo.x), f(hi.x), f(lo.y), f(hi.y), f(lo.z), f(hi.z)))
    g.append("")
    g.append("} // namespace cart")
    g.append("} // namespace royale")
    with open(GEOMETRY, "w") as fh:
        fh.write("\n".join(g) + "\n")
    print("wrote %s (%d vertices, %d batches, %d triangles) and %s" % (MODEL, len(verts), len(batches), len(tris), GEOMETRY))


if __name__ == "__main__":
    main()
